<%@ Page Language="C#" MasterPageFile="~/Portal/PortalMaster.master" AutoEventWireup="true"
    CodeFile="ManageRoles.aspx.cs" Inherits="RoleManagement_ManageRoles" Title="Manage Roles" %>

<asp:Content ID="Content2" ContentPlaceHolderID="HeaderContainer" runat="server">
    <script src='<%# ResolveUrl ("~/App_Resources/js/framework/jquery.ui.core.js") %>' type="text/javascript"></script>
    <script src='<%# ResolveUrl ("~/App_Resources/js/framework/jquery.ui.datepicker.js") %>' type="text/javascript"></script>


    <link href="../../App_Resources/bootstrap-3.3.1-dist/dist/css/bootstrap.css" rel="stylesheet" />
     <script src="../../App_Resources/js/jgrowl/jquery.jgrowl.js" type="text/javascript"></script>
    <script src="../../App_Resources/js/jgrowl/jquery.ui.all.js" type="text/javascript"></script>
    <link href="../../App_Resources/js/jgrowl/jquery.jgrowl.css" rel="stylesheet" type="text/css" />


</asp:Content>

<asp:Content ID="Content1" ContentPlaceHolderID="BodyContent" runat="Server">
    <div class="panel panel-info">
        <div class="panel-heading">Manage Roles</div>
        <div class="panel-body">
            <p>
                In this page you will be able to view the list of all access roles and create new. Click on the appropriate
        buttons to delete, insert or update a role.
            </p>

            <asp:ScriptManager ID="scriptManager" runat="server" />
            <label>Create a New Role </label>
            <b></b>
            <asp:TextBox ID="RoleName" runat="server"></asp:TextBox>
            <asp:LinkButton CssClass="btn btn-primary btn-sm"   runat="server" ID="btn_CreateRole" Text="Create Role"
                OnClick="CreateRoleButton_Click" />


            <br />

            </div>
            <div class="panel-body">
           <h5  class="text-primary">Roles</h5>

            <asp:UpdatePanel ID="upd" runat="server">
                
                <ContentTemplate>

                    <div class="grid_9 omega align-right">
                        <asp:UpdateProgress ID="UpdateProgress1" runat="server">
                            <ProgressTemplate>
                                <img src="../../App_Resources/images/loader-life.gif" alt="Loading Data" />
                            </ProgressTemplate>
                        </asp:UpdateProgress>
                    </div>
                    <div class="grid-viewer grid_19 clearfix">
                        <asp:Literal EnableViewState="false" runat="server" ID="ltlMessage"></asp:Literal>


                        <asp:GridView ID="grid_roles_list" runat="server" OnRowDeleting="grid_roles_list_RowDeleting"
                            AutoGenerateDeleteButton="True" AutoGenerateColumns="False" SkinID="GridView" PageSize="20">
                            <Columns>
                                <asp:TemplateField HeaderText="Role">
                                    <ItemTemplate>
                                        <asp:Label runat="server" ID="RoleNameLabel" Text='<%# Container.DataItem %>' />
                                    </ItemTemplate>
                                </asp:TemplateField>
                            </Columns>
                        </asp:GridView>



                    </div>
                    <div class="clearfix">
                    </div>
                    <div class="clearfix align-right">
                    </div>
                </ContentTemplate>
            </asp:UpdatePanel>


        </div>

    </div>


</asp:Content>

