<%@ Page Language="C#" MasterPageFile="~/Portal/PortalMaster.master" AutoEventWireup="true"
    CodeFile="UsersAndRoles.aspx.cs" Inherits="RoleManagement_UsersAndRoles" Title="Uses and Roles" %>



<asp:Content ID="Content2" ContentPlaceHolderID="HeaderContainer" runat="server">

    <link href="../../App_Resources/bootstrap-3.3.1-dist/dist/css/bootstrap.css" rel="stylesheet" />
    <script src="../../App_Resources/js/jgrowl/jquery.jgrowl.js" type="text/javascript"></script>
    <script src="../../App_Resources/js/jgrowl/jquery.ui.all.js" type="text/javascript"></script>
    <link href="../../App_Resources/js/jgrowl/jquery.jgrowl.css" rel="stylesheet" type="text/css" />

</asp:Content>



<asp:Content ID="Content1" ContentPlaceHolderID="BodyContent" runat="Server">

    <div class="panel panel-info">
        <div class="panel-heading">Roles & Users</div>
        <div class="panel-body">
            <p>
                In this page you will be able to view the list of all access roles and users who have access to. 
            </p>

            <p align="center">
                <asp:Label ID="ActionStatus" runat="server" CssClass="Important" Visible="false"></asp:Label>
            </p>

            <div class="accountInfo">
                <fieldset class="login">
                     
                     
                    <h5  class="text-primary">Manage Roles By User</h5>


                    <p>
                        <b>Select an User:</b>
                        <asp:DropDownList ID="UserList" runat="server"  AutoPostBack="True" DataTextField="UserName" DataValueField="UserName" OnSelectedIndexChanged="UserList_SelectedIndexChanged"></asp:DropDownList>
                    </p>

                    <p>
                        <asp:Repeater ID="UsersRoleList" runat="server" >
                            <ItemTemplate> 
                                
                                <asp:CheckBox runat="server" ID="RoleCheckBox" class="btn btn-default btn-sm" style="margin-bottom:5px;" AutoPostBack="true" Text='<%# Container.DataItem %>' OnCheckedChanged="RoleCheckBox_CheckChanged" />
                                 
                            </ItemTemplate>
                        </asp:Repeater>
                    </p>
                </fieldset>

            </div>

            <div class="accountInfo">
                <fieldset class="login">
                     
                    <h5  class="text-primary">Manage Users By Role</h5>


                    <p>
                        <b>Select a Role:</b>
                        <asp:DropDownList ID="RoleList" runat="server" AutoPostBack="true" OnSelectedIndexChanged="RoleList_SelectedIndexChanged"></asp:DropDownList>
                    </p>
                    <p>
                        <asp:GridView ID="RolesUserList" runat="server" OnRowDeleting="RolesUserList_RowDeleting"
                            AutoGenerateDeleteButton="True" AutoGenerateColumns="False" EmptyDataText="No users belong to this role."
                            SkinID="GridView" GridLines="None">

                            <Columns>
                                <asp:TemplateField HeaderText="Users">
                                    <ItemTemplate>
                                        <asp:Label runat="server" ID="UserNameLabel" Text='<%# Container.DataItem %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                            </Columns>


                        </asp:GridView>
                    </p>

                </fieldset>

            </div>
        </div>
    </div>


</asp:Content>
